name: Check code with linter and tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Build
        run: |
          npm install
          npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Build
        run: |
          npm install
          npm run test:ci
